version: "3.9"
services:
    web:
        build: .
        command: uvicorn main:app --workers 2 --host 0.0.0.0
        env_file:
            - .env
        volumes:
            - .:/code
        ports:
            - 8000:8000

    celery:
        build: .
        env_file:
            - .env
        command: celery -A worker worker -l info
        volumes:
            - .:/code
